version: "3.9"

services:
  # ==========================
  # Kubernetes (k3s) Deployment
  # ==========================
  k3s:
    image: rancher/k3s:v1.29.1-k3s1
    container_name: kubernetes
    privileged: true
    command: server --disable traefik
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=644
    volumes:
      - k3s-data:/var/lib/rancher/k3s
      - ./data/kubeconfig:/output
    ports:
      - "6443:6443"  # Kubernetes API server

volumes:
  k3s-data: