apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logistic-production
  template:
    metadata:
      labels:
        app: logistic-production
    spec:
      containers:
      - name: logistic-production
        image: logistic-production:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

        resources:
          limits:
            nvidia.com/gpu: 1

        volumeMounts:
        - name: model-volume
          mountPath: /app/model

        - name: rag-volume
          mountPath: /app/rag

      volumes:
      - name: model-volume
        hostPath:
          path: /data/model

      - name: rag-volume
        hostPath:
          path: /data/rag