apiVersion: apps/v1
kind: Service
metadata:
  name: logistic-production-service
spec:
  selector:
    app: logistic-production
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000