# Create docker-compose.yml for MLflow
version: "3.9"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow-server
    ports:
    - "5015:5000"
    env_file:
      - ../api/app/.emv
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9015
    volumes:
      - mlflow_db:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: mlflow-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../api/app/.emv
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:RELEASE.2024-01-16T16-10-20Z
    container_name: minio-init
    depends_on:
      - minio
    env_file:
      - ../api/app/.emv
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
      mc mb -p local/mlflow &&
      mc anonymous set download local/mlflow &&
      exit 0
      "

volumes:
  mlflow_db:
  minio_data: