version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow-server
    ports:
      - "5015:5000"
    env_file:
      - ../api/app/.env
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - mlflow_db:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root s3://mlflow
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: mlflow-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../api/app/.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mlflow_db:
  minio_data: